### ISSUE TITLE
Apache Storm 1.1.0 中文文档，大哥您有兴趣嘛 。。。

### ISSUE THREAD

**Issue by wangyangting** [weyo/Storm-Documents#2]
Apache Storm 1.1.0 中文文档
1. 网页地址: <http://storm.apachecn.org/releases/cn/1.1.0>
2. github: <https://github.com/apachecn/storm-doc-zh>

在网上搜索发现了大哥您的 Storm 中文文档，找了半天大哥您的联系方式，还是没找到，所以来提个 Issue，看能不能联系下您，打扰之处抱歉了 。。。

由于最近组织翻译了 [Storm 1.1.0 中文文档](http://storm.apachecn.org/releases/cn/1.1.0/)，然后看到大哥您也翻译了该文档，所以想来问下大哥您有木有兴趣来弄弄，或者有兴趣聊一下之类的，打扰之处实在抱歉了哈！~~~

**Comment by weyo** [comment]
非常感谢您的邀请！很抱歉现在才看到issue，刚也看了你们的网站，做的真的是非常有水准，国内有这样踏实能干的翻译团队真的很赞。不过因为我目前已经转到其他方向了，Storm这块关注得相对少点，而且看到你们的文档已经翻译得差不多了，就不掺和给你们添麻烦了。另外，我的邮箱是 ivicoco@gmail.com，如果有其他需要，也欢迎随时和我联系，谢谢！
